### PR TITLE
Restructure package sec

### LINKED ISSUE #114: Fix CI
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-africa/pypsa-earth-sec/tree/main) branch or the latest [release](https://github.com/pypsa-meets-africa/pypsa-earth-sec/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-africa` environment](https://github.com/pypsa-meets-africa/pypsa-africa/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

The CI is not working, there is the need to update the testing config file to adapt it to make the CI work

### PR DESCRIPTION
**Pull request by davide-f**
# Closes #114

## Changes proposed in this Pull Request
The goal of this PR is to mirror the https://github.com/pypsa-meets-africa/pypsa-africa/pull/355 to let the Sec model work after that PR.
This is currently a draft so to possibly comment on it and open the discussion for a better organization of the folder for readability purposes

## Checklist

- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [x] Newly introduced dependencies are added to `envs/environment.yaml` and `envs/environment.docs.yaml`.
- [x] Changes in configuration options are added in all of `config.default.yaml`, `config.tutorial.yaml`, and `test/config.test1.yaml`.
- [x] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [x] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Comment by davide-f** [comment]
@Hazem-IEG @energyLS 
While revising the method and enable the CI back, I encountered some bugs that I tried to solve.
There are some changes that have been done, most of which I am confident of.
Please, revise the PR and in particular this commit: https://github.com/pypsa-meets-africa/pypsa-earth-sec/pull/129/commits/cbfdd6c4648bac790e2911a337aba274d5fe746e
I had to comment some parts out and it should be understood whether that is expected or not

**Comment by Hazem-IEG** [comment]
@davide-f, Looks good at a first glance. I'm currently neck-deep in validating the model in conjunction with the old structure of pypsa-earth to showcase the model on Thursday. 
I would then merge it early August unless it helps @energyLS with the current problems he has.

**Comment by energyLS** [comment]
Thanks @davide-f! I will have a closer look, might help a lot for my current workflow issues. I agree on merging early August to not interfere with @Hazem-IEGs current work, but I will switch to the branch for testing.

**Review by energyLS — COMMENTED** [review]
Great work, will be merged now. We expect the CI to fail though, since some additions to this branch were made to avoid merge conflicts. Next step: get the CI running

**Review by energyLS — APPROVED** [review]

**Pull request merged**
