### PR TITLE
Pypsa africa integration

### PR DESCRIPTION
**Pull request by davide-f**
This PR aims at integrating the PyPSA-Earth-Sec workflow and the PyPSA-Africa(Earth) one.

It is running, but since it is a major change, I keep it in draft mode and needs to be crossverified.

### CODE REVIEW

**Comment by davide-f** [comment]
To be done:
- [ ] single configuration file for both
- [ ] revise the check

**Comment by davide-f** [comment]
This PR now works, though the model for NG is still infeasible.
Need some crosschecking

**Comment by davide-f** [comment]
The infeasibility disappears when land_transport_electric_share is deactivated (set to 0.0).
I tested also a very small number (0.0001) but the error still persists; my feeling is lack of enough generation capacity somewhere.

Did you experience such problem?

**Comment by davide-f** [comment]
This PR is ready and can be merged.
The CI on windows does not work but it is a bit weird: it may be like the relative paths on windows are not well accepted in subworkflows.
I disabled the windows CI temporarily

**Comment by davide-f** [comment]
@Hazem-IEG @energyLS I'm having problems in integrating the add_heat in the workflow. May I comment it out and then we check how to merge it?
I also needed some adaptations with respect to the new merge; we absolutely need the CI to be integrated otherwise it's becoming complex to maintain the package

**Comment by energyLS** [comment]
Yes please go ahead and commit it out, and we can discuss it tomorrow. Do you need support with anything?

**Pull request merged**
