### PR TITLE
Pre commit

### LINKED ISSUE #74: Revise restyler with pre-commit

### PR DESCRIPTION
**Pull request by davide-f**
This PR aims at including the pre-commit.

Once included, we will need to run it on all scripts and it will create a ton of merge conflicts in the meantime.
So, before doing that, we need alignment

Closes #74

### CODE REVIEW

**Comment by davide-f** [comment]
@Hazem-IEG @energyLS This PR is ready, but before merging, it needs coordination

**Comment by davide-f** [comment]
> what do you mean with coordination? @davide-f

@Hazem-IEG to successfully implement the pre-commit we need to run it through all the files in the repo. I did it locally but the output is that basically all files are modified.
Thus once merged it would create a ton of merge conflicts to all the other branches which they may create problems to all of us, including myself with the parallel branch.
That's why before completing the pre-commit merge, I strongly recommend all of us to merge parallel branches at good stage of development, not to incur into merge conflicts that may be annoying to address.

Do you have parallel branches with a lot of developments that need to be merged first? If so, we can wait before merging.
Otherwise, if the merge conflicts are too many, sometimes it may be easier to start from a parallel new branch and re-implement the changes.

For example, I do have a parallel PR that has a lot of changes, if I merge and run the pre-commit without first merging the other PR it becomes difficult to fix the merge conflicts I fear.

**Comment by energyLS** [comment]
@davide-f I think this PR is ready, Hazem has merged the remaining parallel branches on Friday. So there shouldn't be any major parallel developments. If you don't see any issues either, I will merge this PR?

**Comment by davide-f** [comment]
The restyled-io has been disabled for pypsa-earth-sec from now on

**Pull request merged**
